name: Upload to Pages

on:
  push:
    branches: [main]

jobs:
  create-files:
    runs-on: ubuntu-latest
    container:
      image: "swift:5.2"
    steps:
    - name: Checkout-to-branch
      uses: actions/checkout@v2

    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Generate Site
      run: |
        cp Resources/GaldinerisTheme/styles.css Resources 
        publish generate

    - name: Update gh-pages branch
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: Output
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
